// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmkesfrgoisfopgqdccj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpta2VzZnJnb2lzZm9wZ3FkY2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Nzk1NjQsImV4cCI6MjA3MzM1NTU2NH0.Tc_w5IFTAYOK4KUxUzJL4M-x8S2vfkRzM6RCqCZM1XI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});